services:
  database:
    image: postgres:15-alpine
    container_name: expiry-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${EXTERNAL_PORT_DB}:${INTERNAL_PORT_DB}"
    networks:
      - expiry-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    healthcheck:
      # Usa el puerto interno variable para el chequeo
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER} -d ${DB_NAME} -p ${INTERNAL_PORT_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  db-admin:
    image: dpage/pgadmin4
    container_name: expiry-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "127.0.0.1:${EXTERNAL_PORT_PGADMIN}:${INTERNAL_PORT_PGADMIN}"
    networks:
      - expiry-network
    volumes:
      - ./infra/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      database:
        condition: service_healthy

  core-api:
    build: ./core-api
    container_name: expiry-core
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "127.0.0.1:${EXTERNAL_PORT_API}:${INTERNAL_PORT_API}"
    environment:
      SERVER_PORT: ${INTERNAL_PORT_API}
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:${INTERNAL_PORT_DB}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SECURITY_JWT_SECRET: ${JWT_SECRET}
      SECURITY_JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_DAYS}
    networks:
      - expiry-network
    deploy:
      resources:
        limits:
          memory: 768M
    depends_on:
      database:
        condition: service_healthy

networks:
  expiry-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
