spring:
  application:
    name: expiry-tracker-core

  datasource:
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # Las tablas se crean autom√°ticamente
    properties:
      hibernate:
        format_sql: true # Para que el SQL en consola sea legible
